### ISSUE TITLE
Make created docker image publicly available

### ISSUE THREAD

**Issue by papauorg** [PiBrewing/craftbeerpi4#101]
The docker image that is created via the build pipeline in this repo is not publicly available. I noticed that when I was trying to update the image of my brewery setup:

```
[+] Building 0.3s (3/3) FINISHED                                                                                        
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 105B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for ghcr.io/pibrewing/craftbeerpi4:v4.1.6                                       0.3s
------
 > [internal] load metadata for ghcr.io/pibrewing/craftbeerpi4:v4.1.6:
------
failed to solve: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```
Also it is not visible when viewing the repo in the browser when not logged in to github:
![Missing packages](https://user-images.githubusercontent.com/2471424/224539609-fc32239b-151b-42b1-a9f6-7bc0e176a315.png)

**Please change the package settings of the docker image so it can be downloaded anonymously and so can be used by whoever wants to without a login.**

Here is the github documentation on how this can be done:
https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-packages-for-an-organization

Best regards,
Philipp

**Comment by avollkopf** [comment]
@papauorg  Had to enable public option first for the org as possibility and changed it now for the repo. Can you test if it is working and report back.

**Comment by papauorg** [comment]
@avollkopf Perfect! The images are visible in the browser and can be downloaded via docker. Thanks
