### ISSUE TITLE
New test branches for Server and UI

### ISSUE THREAD

**Issue by avollkopf** [PiBrewing/craftbeerpi4#107]
@dereulenspiegel , @papauorg , @pascal1404 , @papauorg 

I have created new branches for [Server](https://github.com/PiBrewing/craftbeerpi4/tree/plugin-settings-selection-test) and [UI](https://github.com/PiBrewing/craftbeerpi4-ui/tree/plugin-settings-selection-test) with a small enhancement for the Settings page. There are now setting categories.

Default is currently All, craftbeerpi and steps. There is also hidden which is not shown in the settings. 'All' does only filter hidden category.

The installed plugins are also listed as categories.

Configupdate is adding the categories automatically after first start of the branches (plugin-settings-selection-test) to the existing settings. (steps, craftbeerpi, hidden).

Installed plugins are currently listed under craftbeerpi, but user can change the config file manually. Plugins that add global settings will require small updates (like it is done in the configupdate extension) to adapt the new settings 'source' parameter.

This will give  better overview on the settings page. What do you guys think

![image](https://user-images.githubusercontent.com/43980694/229361392-3fa0b23a-9edc-4fa8-966d-880117f2a716.png).

Example with manually adapted parameters for the cbpi4-LCDisplay Plugin:
![image](https://user-images.githubusercontent.com/43980694/229361961-ab19ee1a-48f5-4c75-9882-f4170ee633dc.png)

**Comment by dimontau** [comment]
Greetings. After the update, I lost everything. The server does not start. Gives such an error. I tried to put on a new system, the same error. What can be wrong?
I use Raspberry Pi Zero.
![12341](https://user-images.githubusercontent.com/24360134/229870273-fbaa3b8f-61d2-4b91-aae9-3d761c6cc9f6.png)

**Comment by avollkopf** [comment]
@dimontau The new 'plugins-settings-selection-test' branches of Server and UI are only meant for development and not for usage. Please revert back to the main branch. Not sure what branch you were trying with the setup of a new system. If it is not this branch. Please open a new issue.

**Comment by avollkopf** [comment]
Setup.py will require an additional parameter for this functionality as it can be seen [here](https://github.com/PiBrewing/cbpi4-system/blob/development/setup.py#L16)

`keywords='globalsettings'`

is required as cbpi checks this parameter and adds then the plugin to the drop down menu on the settings page

**Comment by avollkopf** [comment]
When adding parameters, you need to do it now this way:
```python
        if autoreboot is None:
            logger.info("INIT AutoReboot parameter")
            try:
                await self.cbpi.config.add("AutoReboot", "No", type=ConfigType.SELECT, description="Reboot Pi once a day at selected time",
                                                                                                    options=[{"label": "Yes", "value": "Yes"},
                                                                                                        {"label": "No", "value": "No"}],
                                                                                                        source="cbpi4-system")
            except:
                logger.warning('Unable to update config')```

type, description, options and source need to be used in front of the values. Options can be also omitted if not required.

source must match your plugin name.

**Comment by avollkopf** [comment]
to update existing plugins I am using also an additional parameter related to the plugin version to check the update.
```python
        plugin = await self.cbpi.plugin.load_plugin_list("cbpi4-system")
        self.version=plugin[0].get("Version","0.0.0")

        self.system_update = self.cbpi.config.get("system_update", None)
```

Plugin version is then later checked and plugin updates the parameter if flag is not in the settings or has an older version. In this case, the value of the parameter is used:
```python
if autoreboot is None:
            logger.info("INIT AutoReboot parameter")
            try:
                await self.cbpi.config.add("AutoReboot", "No", type=ConfigType.SELECT, description="Reboot Pi once a day at selected time",
                                                                                                    options=[{"label": "Yes", "value": "Yes"},
                                                                                                        {"label": "No", "value": "No"}],
                                                                                                        source="cbpi4-system")
            except:
                logger.warning('Unable to update config')
        else:
            if self.system_update == None or self.system_update != self.version:
                try:
                    await self.cbpi.config.add("AutoReboot", autoreboot, type=ConfigType.SELECT, description="Reboot Pi once a day at selected time",
                                                                                                    options=[{"label": "Yes", "value": "Yes"},
                                                                                                        {"label": "No", "value": "No"}],
                                                                                                        source="cbpi4-system")
                except:
                    logger.warning('Unable to update config')               
```

**Comment by avollkopf** [comment]
Finally, plugin update parameter is added to the settings:
```python
        if self.system_update == None or self.system_update != self.version:
            try:
                 await self.cbpi.config.add("system_update", self.version,type=ConfigType.STRING,description="cbpi4 system version update",source="hidden")         
            except Exception as e:
                logger.warning('Unable to update config') 
                logger. Warning(e)
```

source is set to 'hidden' -> Parameter does not show up un settings page (even with 'All')

This parameter can then be used for updates. (It is not really required for new plugins as there one can add the source parameter upfront)

**Comment by avollkopf** [comment]
Changed the plugins a bit and also craftbeerpi to allow for removal of obsolete parameters in case you remove a plugin.

Example is [here](https://github.com/PiBrewing/cbpi4-system/blob/0f797b37877ad9a8a1f20a1220c3b15b3f9ffd71/cbpi4-system/__init__.py#L28)

and [here](https://github.com/PiBrewing/cbpi4-system/blob/0f797b37877ad9a8a1f20a1220c3b15b3f9ffd71/cbpi4-system/__init__.py#L66)

This will update parameters in case of installation of plugin or new plugin version.

cbpi4 has the api option to remove obsolte parameters from the config.json file -> https://github.com/PiBrewing/craftbeerpi4/blob/f990e0e0a35ba9b4259d254abcdbfeef0ebade13/cbpi/http_endpoints/http_config.py#L107

**Comment by avollkopf** [comment]
merged into development
