### ISSUE TITLE
potential issue with latest release and armv6 devices (Pi Zero W) -> Illegal Instruction

### ISSUE THREAD

**Issue by avollkopf** [PiBrewing/craftbeerpi4#108]
There seems to be a potential issue with older armv6 based systems and the latest releases of craftbeerpi4.  User @dimontau has reported this issue [here](https://github.com/PiBrewing/craftbeerpi4/issues/107#issuecomment-1496339384). 

The [issue](https://github.com/piwheels/packages/issues/348) must be related to the required upgrade of the cryptography package to package versions > 39.0.1 due to [security issues](https://github.com/craftbeerpi/craftbeerpi4/security/dependabot/3)

Not sure if there is already a fix for these systems, but I will change the dependency for the [development branch](https://github.com/PiBrewing/craftbeerpi4/tree/development) to cryptography 40.0.1 as there seems to be some fix for [32 bit systems](https://cryptography.io/en/latest/changelog/#v40-0-1). However, I am not able to test it myself

**Comment by dimontau** [comment]
Tried today's update. Everything remains the same.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Apr 5 15:21:40 2023 from 192.168.1.100
pi@raspberrypi:~ $ sudo cbpi start
Illegal instruction

**Comment by avollkopf** [comment]
@dimontau not sure, if this will help, but on 64 bit systems there is a different issue after cryptography upgrade which can be solved: https://openbrewing.gitbook.io/craftbeerpi4_support/readme/troubleshooting/cryptography_update.

Not sure, if this will help... Bit I fear, they only way is mentioned in my message before.

**Comment by dimontau** [comment]
I haven't been able to verify this yet. For some reason, there is a problem with connecting to the Raspberry servers.
As soon as I try it, I will write about the result.

**Comment by dimontau** [comment]
Greetings. I finally got it working according to your instructions. Will I be able to solve this problem with new updates in the future as well?

**Comment by avollkopf** [comment]
> Greetings. I finally got it working according to your instructions. Will I be able to solve this problem with new updates in the future as well?

Ok, this is good. With respect to future versions, it'll get more unlikely that it can be solved as other dependencies may require the latest cryptography version in future (e.g. aiohttp). Not sure if the cryptography coders can solve this. If not,  a pi zero 2 should be working as the quad core upgrade should be comparable to the pi3/4 in terms of the os requirements

**Comment by avollkopf** [comment]
It is probably more an issue in pywheels when they build the package.

**Comment by dimontau** [comment]
Hello, Alexander. Off topic, but I don't know where else to post. Can you help me redesign the cbpi4-Flowmeter plugin? I don't know python myself. I constantly have an error with the volume of water, since the speed of the water is not constant. Is it possible to change the code or add to the code the ability to calculate the volume of water by the number of pulses per liter, and not by frequency? The documentation says that there are 450 pulses per liter. Well, so that you can change the number of pulses in the settings. The author of the plugin does not get in touch. I tried this with an arduino. It turns out high accuracy to measure the amount of water, regardless of the flow rate.

**Comment by avollkopf** [comment]
@dimontau I have referenced it in the corresponding plugin where it belongs to. It is not recommended to 'hijack' a different issue.

**Comment by avollkopf** [comment]
added info to changes and troubleshooting
