### ISSUE TITLE
new plugin 

### ISSUE THREAD

**Issue by dimontau** [PiBrewing/craftbeerpi4#112]
Hello. I wrote a temperature sensor plugin for max6675. You can add it to the plugin directory. I think it will be useful to those who use gas burners to control the burning of gas. The plugin cbpi4-pt100x was taken as a basis.
The plugin has been tested and is fully functional.
https://github.com/dimontau/cbpi4-max6675/tree/main

**Comment by avollkopf** [comment]
Added to the documentation, but next issue with respect to documentation should be created in the documentation repo. I will also open an issue at the repo to add more details on the sensor types, hardware config
