### ISSUE TITLE
"CS pin already used. Must be exclusive!" ADS1256 SPI communication

### ISSUE THREAD

**Issue by mjiao5151** [PiBrewing/craftbeerpi4#115]
Try to write a plugin to read analog signals with the help of an  ADS1256 ADC module.
the ADC module has 8 analog inputs, and communicates with rpi via SPI bus.
the plugin works fine with only one AI channel configured in cbpi4, but will report error when additional channels were configured.
the error message was "CS pin already used. Must be exclusive!" 

I am wondering what is the cause of this issue, any help will be greatly appreciated!
thansk!

**Comment by prash3r** [comment]
from this information alone i would guess your implementation results in every configured channel to try and manage the SPI bus itself. the first channel creates the SPI bus, acts as a SPI bus master and works fine and the second channel also tries to create the SPI bus on the same cbpi pins but cant because they are of course already in use by the other channel as all the channels should be running via the same SPI bus.

there are multiple ways to implement this but the important thing is that the channels need to use the same SPI BUS and not try to create one each.

I wasnt able to find the repo you are talking about. Maybe your repo is private or offline? If you want me to have a look make it available and link it here.

I will soon close this issue as it has nothing to do with the main repo. There soon will be proper channels for requesting plugin dev support from the community.

**Comment by mjiao5151** [comment]
prash3r
thank you for your quick reply, I agree with your conclusion, but have no idea how to implement.
the code is based on a ads1256 wrapper from here: https://github.com/ul-gh/PiPyADC/

my code was simple, one config file and a __init__.py file.

`python
# -*- coding: utf-8 -*-
import os
import time
from aiohttp import web
import logging
from unittest.mock import MagicMock, patch
import asyncio
import random
from cbpi.api import *
from pipyadc import ADS1256
from pipyadc.ADS1256_definitions import *
import cbpi4_analog_sensor.board_config


logger = logging.getLogger(__name__)

POTI = POS_AIN0 | NEG_AINCOM
LDR = POS_AIN1 | NEG_AINCOM
CH2 = POS_AIN2 | NEG_AINCOM
CH3 = POS_AIN3 | NEG_AINCOM
CH4 = POS_AIN4 | NEG_AINCOM
CH5 = POS_AIN5 | NEG_AINCOM
CH6 = POS_AIN6 | NEG_AINCOM
CH7 = POS_AIN7 | NEG_AINCOM

# Arbitrary length tuple of input channel pair values to scan sequentially
CH_SEQUENCE = (POTI, LDR, CH2, CH3, CH4, CH5, CH6, CH7)

@parameters([
    Property.Select(label="ADSchannel", options=[0,1,2,3,4,5,6,7], description="Enter channel-number of ADS125x"),
    Property.Select("sensorType", options=["Voltage","Digits","Pressure","Liquid Level","Volume"], description="Select which type of data to register for this sensor"),
    Property.Select("pressureType", options=["kPa","PSI"]),
    Property.Number("voltLow", configurable=True, default_value=0, description="Pressure Sensor minimum voltage, usually 0"),
    Property.Number("voltHigh", configurable=True, default_value=5, description="Pressure Sensor maximum voltage, usually 5"),
    Property.Number("pressureLow", configurable=True, default_value=0, description="Pressure value at minimum voltage, value in kPa"),
    Property.Number("pressureHigh", configurable=True, default_value=10, description="Pressure value at maximum voltage, value in kPa"),
    Property.Number("sensorHeight", configurable=True, default_value=0, description="Location of Sensor from the bottom of the kettle in inches"),
    Property.Number("kettleDiameter", configurable=True, default_value=0, description="Diameter of kettle in inches"),
    Property.Select(label="Interval", options=[1,5,10,30,60], description="Interval in Seconds"),
    Property.Kettle(label="Kettle", description="Reduced logging if Kettle is inactive (only Kettle or Fermenter to be selected)"),
    Property.Fermenter(label="Fermenter", description="Reduced logging in seconds if Fermenter is inactive (only Kettle or Fermenter to be selected)"),
    Property.Number(label="ReducedLogging", configurable=True, description="Reduced logging frequency in seconds if selected Kettle or Fermenter is inactive (default: 60 sec | disabled: 0)")
])
class Analog_Sensor(CBPiSensor):
    
    def __init__(self, cbpi, id, props):
        super(Analog_Sensor, self).__init__(cbpi, id, props)
        
        self.value = 0
        self.value_old = 0
        self.Interval = int(self.props.get("Interval",5))
        # Variables to be used with calculations
        self.GRAVITY = 9.807
        self.PI = 3.1415
        # Conversion values
        self.kpa_psi = 0.145
        self.bar_psi = 14.5038
        self.inch_mm = 25.4
        self.gallons_cubicinch = 231
        
        self.sensorHeight = float(self.props.get("sensorHeight", 0))
        self.kettleDiameter = float(self.props.get("kettleDiameter", 0))
        self.ADSchannel = int(self.props.get("ADSchannel", 0))
        self.pressureHigh = self.convert_pressure(int(self.props.get("pressureHigh", 10)))
        self.pressureLow = self.convert_pressure(int(self.props.get("pressureLow", 0)))
        #logging.info('Pressure values - low: %s , high: %s' % ((pressureLow), (pressureHigh)))
        # We need the coefficients to calculate pressure for the next step
        # Using Y=MX+B where X is the volt output difference, M is kPa/volts or pressure difference / volt difference
        #  B is harder to explain, it's the offset of the voltage & pressure, ex:
        #    if volts were 1-5V and pressure was 0-6kPa
        #    since volts start with 1, there is an offset
        #    We calculate a value of 1.5kPa/V, therefore 1V = -1.5
        #    if the output of the sensor was 0-5V there would be no offset
        self.calcX = int(self.props.get("voltHigh", 5)) - int(self.props.get("voltLow", 0))
        #logging.info('calcX value: %s' % (calcX))
        self.calcM = (self.pressureHigh - self.pressureLow) / self.calcX
        #logging.info('calcM value: %s' % (calcM))
        self.calcB = 0
        if int(self.props.get("voltLow", 0)) > 0:
            self.calcB = (-1 * int(self.props.get("voltLow", 0))) * self.calcM
        #logging.info('calcB value: %s' % (calcB))
        
        # self.value_old = 9999
        # defines how ofte a large delta can be rejected
        self.max_counter = 2
        # counts subsequent rejected values
        self.counter = 0

        self.lastlog=0
        self.sensor=self.get_sensor(self.id)

        self.reducedfrequency=float(self.props.get("ReducedLogging", 60))
        if self.reducedfrequency < 0:
            self.reducedfrequency = 0
            
        
        self.kettleid=self.props.get("Kettle", None)
        self.fermenterid=self.props.get("Fermenter", None)

        self.reducedlogging=True if self.kettleid or self.fermenterid else False

        if self.kettleid is not None and self.fermenterid is not None:
            self.reducedlogging=False
            self.cbpi.notify("OneWire Sensor", "Sensor '" + str(self.sensor.name) + "' cant't have Fermenter and Kettle defined for reduced logging.", NotificationType.WARNING, action=[NotificationAction("OK", self.Confirm)])

        if (self.reducedfrequency != 0) and (self.Interval >= self.reducedfrequency):
            self.reducedlogging=False
            self.cbpi.notify("OneWire Sensor", "Sensor '" + str(self.sensor.name) + "' has shorter or equal 'reduced logging' compared to regular interval.", NotificationType.WARNING, action=[NotificationAction("OK", self.Confirm)])


        self.ads = ADS1256(cbpi4_analog_sensor.board_config)
    
    def convert_pressure(self, value):
        if self.props.get("pressureType", "kPa") == "PSI":
            return value * self.kpa_psi
        else:
            return value
    
    def convert_bar(self, value):
        if self.props.get("pressureType", "kPa") == "PSI":
            return value / self.bar_psi
        else:
            return value / 100

    async def run(self):
        self.ads.drate = DRATE_100
        self.ads.cal_self()
        
        self.kettle = self.get_kettle(self.kettleid) if self.kettleid is not None else None 
        self.fermenter = self.get_fermenter(self.fermenterid) if self.fermenterid is not None else None

        while self.running is True:
           

            self.temp = self.ads.read_continue(CH_SEQUENCE)
            # if self.value_old == 9999:
            #     self.value_old = self.temp[self.ADSchannel]
            chan = self.temp[self.ADSchannel]
            # if self.ADSchannel == 0:
            #     chan = AnalogIn(ads, ADS.P0)
            # elif self.ADSchannel == 1:
            #     chan = AnalogIn(ads, ADS.P1)
            # elif self.ADSchannel == 2:
            #     chan = AnalogIn(ads, ADS.P2)
            # elif self.ADSchannel == 3:
            #     chan = AnalogIn(ads, ADS.P3)
            voltages = chan * self.ads.v_per_digit
            pressureValue = (self.calcM * voltages) + self.calcB    # "%.6f" % ((calcM * voltage) + calcB)
            #logging.info("pressureValue: %s" % (pressureValue))    #debug or calibration
            
            # Time to calculate the other data values
            
            # Liquid Level is calculated by H = P / (SG * G). Assume the SG of water is 1.000
            #   this is true for water at 4C
            #   note: P needs to be in BAR and H value will need to be multiplied by 100,000 to get mm
            liquidLevel = ((self.convert_bar(pressureValue) / self.GRAVITY) * 100000) / self.inch_mm
            if liquidLevel > 0.49:
                liquidLevel += self.sensorHeight
            
            # Volume is calculated by V = PI (r squared) * height
            kettleRadius = self.kettleDiameter / 2
            radiusSquared = kettleRadius * kettleRadius
            volumeCI = self.PI * radiusSquared * liquidLevel
            volume = volumeCI / self.gallons_cubicinch

            if self.props.get("sensorType", "Liquid Level") == "Voltage":
                self.value = voltages
            elif self.props.get("sensorType", "Liquid Level") == "Digits":
                self.value = chan
            elif self.props.get("sensorType", "Liquid Level") == "Pressure":
                self.value = pressureValue
            elif self.props.get("sensorType", "Liquid Level") == "Liquid Level":
                self.value = liquidLevel
            elif self.props.get("sensorType", "Liquid Level") == "Volume":
                self.value = volume
            else:
                self.value = voltages
            
            self.push_update(self.value)
            if self.reducedlogging:
                    await self.logvalue()
            else:
                    self.log_data(self.value)
                    self.lastlog = time.time()
            await asyncio.sleep(self.Interval)

        async def logvalue(self,value=None):
            currentvalue=self.value if value is None else value
            now=time.time()            
            if self.kettle is not None:
                try:
                    kettlestatus=self.kettle.instance.state
                except:
                    kettlestatus=False
                if kettlestatus:
                    self.log_data(currentvalue)
                    logging.info("Kettle Active")
                    self.lastlog = time.time()
                else:
                    logging.info("Kettle Inactive")
                    if self.reducedfrequency != 0:                    
                        if now >= self.lastlog + self.reducedfrequency:
                            self.log_data(currentvalue)
                            self.lastlog = time.time()
                            logging.info("Logged with reduced freqency")
                            pass   

            if self.fermenter is not None:
                try:
                    fermenterstatus=self.fermenter.instance.state
                except:
                    fermenterstatus=False
                if fermenterstatus:
                    self.log_data(currentvalue)
                    logging.info("Fermenter Active")
                    self.lastlog = time.time()
                else:
                    logging.info("Fermenter Inactive")
                    if self.reducedfrequency != 0:                       
                        if now >= self.lastlog + self.reducedfrequency:
                            self.log_data(currentvalue)
                            self.lastlog = time.time()
                            logging.info("Logged with reduced freqency")
                            pass            


    
    def get_state(self):
        return dict(value=self.value)


def setup(cbpi):
    #cbpi.plugin.register("MyCustomActor", CustomActor)
    cbpi.plugin.register("ADS1256 Sensor", Analog_Sensor)
    #cbpi.plugin.register("MyustomWebExtension", CustomWebExtension)
    pass
`
the config file as:

`python
import logging
from pipyadc.ADS1256_definitions import *
################ Configuration file for one ADS1256 instance  #################
# SPI bus configuration and GPIO pins used for the ADS1255/ADS1256.
#
# These settings are compatible with the "Waveshare High-Precision AD/DA" board.
#
# To create multiple class instances for more than one AD converter, a unique
# configuration must be specified as argument for each instance.

#LOGLEVEL = logging.WARNING
LOGLEVEL = logging.WARNING

# 0 for main SPI bus, 1 for auxiliary SPI bus.
SPI_BUS = 0
# SPI clock rate in Hz. The ADS1256 supports a minimum of 1/10th of the output
# sample data rate in Hz to 1/4th of the oscillator CLKIN_FREQUENCY which
# results in a value of 1920000 Hz for the Waveshare board. However, since
# the Raspberry pi only supports power-of-two fractions of the 250MHz system
# clock, the closest value would be 1953125 Hz, which is slightly out of spec
# for the ADS1256. Choosing 250MHz/256 = 976563 Hz is a safe choice.
#SPI_FREQUENCY = 976563
SPI_FREQUENCY = 976563
# Risking the slightly out-of-spec speed:
#SPI_FREQUENCY = 1953125
# If set to True this will perform a chip reset using the hardware reset line
# when initializing the device.
CHIP_HARD_RESET_ON_START = True

#### Raspberry Pi GPIO configuration ##########################################
# =====> NEW in version 2 since using pigpio instead of wiringpi library:
# =====> Raspberry Pi pinning now uses the Broadcom numbering scheme!

# Tuple of all (chip select) GPIO numbers to be configured as an output and
# initialised to (inactive) logic high state before bus communication starts.
# Necessary for more than one SPI device if GPIOs are not otherwise handled.
#CHIP_SELECT_GPIOS_INITIALIZE = (22, 23)
CHIP_SELECT_GPIOS_INITIALIZE = (22, 23)
# Chip select GPIO pin number.
# This is required as hardware chip select can not be used with the ADS125x
# devices using this library
# CS_PIN      = 22
CS_PIN      = 22
# If DRDY is not connected to an input, a sufficient DRDY_TIMEOUT must be
# specified further below and aquisition will be slower.
#DRDY_PIN    = 17
DRDY_PIN    = 17
# Hardware reset pin is optional but strongly suggested in case multiple devices
# are connected to the bus as the ADS125x will lock-up in case multiple chips
# are selected simultaneously by accident.
#RESET_PIN   = 18 # Set to None if not used.
RESET_PIN   = 18 # Set to None if not used.
# Optional power down pin
#PDWN_PIN    = 27 # Set to None if not used.
PDWN_PIN    = 27 # Set to None if not used.
###############################################################################

##################  ADS1256 Constant Configuration Settings  ##################
# Seconds to wait in case DRDY pin is not connected or the chip
# does not respond. See table 21 of ADS1256 datasheet: When using a
# sample rate of 2.5 SPS and issuing a self calibration command,
# the timeout can be up to 1228 milliseconds:
DRDY_TIMEOUT    = 2
# Optional delay in seconds to avoid busy wait and reduce CPU load when
# polling the DRDY pin. Default is 0.000001 or 1 µs (timing not accurate)
DRDY_DELAY      = 0.000001
# Master clock rate in Hz. Default is 7680000:
CLKIN_FREQUENCY = 7680000
################################################################################


# All following settings are accessible through ADS1256 class properties

##############  ADS1256 Default Runtime Adjustable Properties  #################
# Analog reference voltage between VREFH and VREFN pins
v_ref = 2.5
# Gain seting of the integrated programmable amplifier. This value must be
# one of (GAIN_1, GAIN_2, GAIN_4, GAIN_8, GAIN_16, GAIN_32, GAIN_64).
# Gain = 1, V_ref = 2.5V ==> full-scale input voltage = 5.00V, corresponding
# to a 24-bit two's complement output value of 2**23 - 1 = 8388607
gain_flags = GAIN_1
################################################################################

####################  ADS1256 Default Register Settings  #######################
# REG_STATUS:
# When enabling the AUTOCAL flag: Any following operation that changes
# PGA GAIN, DRATE or BUFFER flags triggers a self calibration:
# THIS REQUIRES an additional timeout via WaitDRDY() after each such operation.
# Note: BUFFER_ENABLE means the ADC input voltage range is limited
# to (AVDD-2V),see datasheet
status = BUFFER_ENABLE
# REG_MUX:
# Default: positive input = AIN0, negative input = AINCOM
mux = POS_AIN0 | NEG_AINCOM
# REG_ADCON:
# Disable clk out signal (if not needed, source of disturbance),
# sensor detect current sources disabled, gain setting as defined above:
adcon = CLKOUT_OFF | SDCS_OFF | gain_flags
# REG_DRATE: 
# 10 SPS places a filter zero at 50 Hz and 60 Hz for line noise rejection
drate  = DRATE_10
# REG_IO: No GPIOs needed
gpio = 0x00
`

**Comment by mjiao5151** [comment]
Dear prash3r
Thank you for your quick reply. 
I pushed my code to github. please see here https://github.com/mjiao5151/cbpi4_analog_sensor


my code is modified from https://github.com/sjhoglund/cbpi4-PressureSensor 
the ads1256 wrapper was from https://github.com/ul-gh/PiPyADC

thanks!

**Comment by mjiao5151** [comment]
> 

Dear prash3r
good news, I got my code working.
I followed the main idea you point out, and worked based on the structure of the plugin [cbpi4-scd30-CO2-Sensor](https://github.com/PiBrewing/cbpi4-scd30-co2-sensor/tree/main/cbpi4-scd30-CO2-Sensor) .
with one class reading the signal and store the data in a global variable, each cbpi sensor only read the cached data.
Which got it working.
Thank you again for pointing out the problem!

Best Regards!

**Comment by avollkopf** [comment]
Great, this would have been also my suggestion (scd30-CO2-Sensor). Activate the chip with the cbpi extension once and add up to 8 sensors via the sensor plugin. A similar actor example could be also this one: https://github.com/PiBrewing/cbpi4-PCF8574-GPIO
