### ISSUE TITLE
Transmission of values from a PT100 to Influx

### ISSUE THREAD

**Issue by userbasti** [PiBrewing/craftbeerpi4#121]
If a pt100 temperature sensor is connected, the value is displayed correctly in CBPi but not passed on to Influx. Values from connected DS18B20 sensors are transmitted correctly. Values from a PT100 sensor connected via MQTTDevice are also transmitted.

**Comment by avollkopf** [comment]
Working on my system since I started with cbpi4. Will look into it, but most likely a local issue on your system. Anyway, must be opened under the pt100x plugin and not for cbpi4

**Comment by userbasti** [comment]
Hello okay. Thanks for the feedback. I have opened the issue under the plugin. Okay, the data from the other sensors (ds18b20) are arriving smoothly. Apart from that, everything is working smoothly. I have also asked in the forum (hobbybrauer.de) whether anyone can reproduce this - unfortunately without success. It would be really great if you could test it on your system.

**Comment by userbasti** [comment]
Hello okay. Thanks for the feedback. I have opened the issue under the plugin. Okay, the data from the other sensors (ds18b20) are arriving smoothly. Apart from that, everything is working smoothly. I have also asked in the forum (hobbybrauer.de) whether anyone can reproduce this - unfortunately without success. It would be really great if you could test it on your system.
