### ISSUE TITLE
rpi-lgpio

### ISSUE THREAD

**Issue by mjiao5151** [PiBrewing/craftbeerpi4#124]
Tried a fresh installation of cbpi 4.3.1 on my rpi 3B+ aboard, the python version is 3.9
Had removed RPi-GPIO package via apt, pip, and pip3.
The newly installed cbpi runs ok, but there is a warning line showed up in start up screens as following:

WARNING  [__init__.py:13] Failed to load RPi.GPIO. Using Mock instead

I am just wondering if this normal? Should I worry about anything?

Thanks!

> *******************************
> START
> 2024-01-10:16:17:40,210 WARNING  [craftbeerpi.py:263] 
>   _____            __ _   ____                 _____ _   _  _   ____  __  
>  / ____|          / _| | |  _ \               |  __ (_) | || | |___ \/_ | 
> | |     _ __ __ _| |_| |_| |_) | ___  ___ _ __| |__) |  | || |_  __) || | 
> | |    | '__/ _` |  _| __|  _ < / _ \/ _ \ '__|  ___/ | |__   _||__ < | | 
> | |____| | | (_| | | | |_| |_) |  __/  __/ |  | |   | |    | |_ ___) || | 
>  \_____|_|  \__,_|_|  \__|____/ \___|\___|_|  |_|   |_|    |_(_)____(_)_| 
>                                                                           
>                                                                           
> 
> 2024-01-10:16:17:40,215 WARNING  [craftbeerpi.py:264] www.CraftBeerPi.com
> 2024-01-10:16:17:40,216 WARNING  [craftbeerpi.py:265] (c) 2021/2022/2023 Manuel Fritsch / Alexander Vollkopf
> 2024-01-10:16:17:40,306 WARNING  [__init__.py:13] Failed to load RPi.GPIO. Using Mock instead
>

**Comment by avollkopf** [comment]
Seems to be, that you are not using bookworm OS if python 3.9 is running. bookworm is using python 3.11 and the recommended 64 bit os.

**Comment by mjiao5151** [comment]
> Seems to be, that you are not using bookworm OS if python 3.9 is running. bookworm is using python 3.11 and the recommended 64 bit os.

Thank you for your reply! 
I tried to switch some gpio pins as cbpi actors, it would not work.
Going to switch to bookworm OS, seems it is the easiest solution.

**Comment by lalo-uy** [comment]
You may try the system.gpio plugin.
I used on cbpi3 for some i2c gpio.

**Comment by mjiao5151** [comment]
Dear Eduardo
Thank you for your informative reply!
I shifted to bookworm before read your comments, still many thanks, It is good to know an alternative.

Best Regards!
