### ISSUE TITLE
Status hendictrl, is it usable?

### ISSUE THREAD

**Issue by heyudude** [PiBrewing/craftbeerpi4#125]
Hi,

Really glad I discovered cbpi4 again, super that you worked on it all!

What is the status of the Hendi controller? I see only an actor works?
Can I brew with it or is it unstable and not advisable to use and help to develop it? Or is there any other way to use the owm steered coocking plate?

Regards

Dude

**Comment by avollkopf** [comment]
I have ported it, but don't know, if anybody is using it. Since I have no hendi, I can't test or confirm.

Anyhow, this question is related to the plugin, but not to cbpi4 itself.

-> please open / post corresponding issues for the plugin repo itself
