### ISSUE TITLE
Plugin creation proplem

### ISSUE THREAD

**Issue by brackendalebrewing** [PiBrewing/craftbeerpi4#128]
Hi first thank you Alexander and every one for the hard work.
I created a test plugin for 4.3.1 following the documentation.  The creation and addition seems to complete with out errors .  The plugin however is not available nor is it listed.  Other plugins installed through pipx and pypl and are available  but installed in a separate python directory.  My testing is on a dell laptop and Ubuntu 22.04.3 LTS

**Comment by avollkopf** [comment]
You need to share more information. Otherwise it is impossible to help. 
- Which plugin (linkt to code,....)
- How did you install the plugin?
- What is the log telling you on startup?
- ...

**Comment by brackendalebrewing** [comment]
Hi
I Want to update some of my old personal plugins ,created on version 4.0.6

I wanted to review the process and look at your sample plugin created using
"CBPI create"
The plugin directory is created and looks correct , the sample plugin
created at that time looks correct and proper



















* cbpi create test_plugin--------------------------Welcome to CBPi
4.3.1--------------------------config folder path :   ./configlogs folder
path   :   /home/a/logs*******************************Debug-log-level is
30*******************************Plugin Creation[?] Plugin Name (will be
prefixed with "cbpi4-"): test_pluginPlugin cbpi4-test-plugin created!
Developer Documentation:
https://openbrewing.gitbook.io/craftbeerpi4_support/readme/development
<https://openbrewing.gitbook.io/craftbeerpi4_support/readme/development>Happy
developing! Cheers*

I then ran
















*$ pipx runpip cbpi4 install -e ./cbpi4-test-plugin Obtaining
file:///home/a/cbpi4/cbpi4-test-plugin  Installing build dependencies ...
done  Checking if build backend supports build_editable ... done  Getting
requirements to build editable ... done  Installing backend dependencies
... done  Preparing editable metadata (pyproject.toml) ... doneBuilding
wheels for collected packages: cbpi4-test-plugin  Building editable for
cbpi4-test-plugin (pyproject.toml) ... done  Created wheel for
cbpi4-test-plugin:
filename=cbpi4_test_plugin-0.0.1-0.editable-py3-none-any.whl size=15002
sha256=dc11bed4efdac8b792f200b14533ae641471ca2852eecb04df249276e8854804
Stored in directory:
/tmp/pip-ephem-wheel-cache-ixpaoikz/wheels/4c/2b/88/4690cb4151ac036476febba1b85d03156eb807632c79cd5f4bSuccessfully
built cbpi4-test-pluginInstalling collected packages:
cbpi4-test-pluginSuccessfully installed cbpi4-test-plugin-0.0.1*

*Then*
cbpi plugins














*--------------------------Welcome to CBPi
4.3.1--------------------------config folder path :   ./configlogs folder
path   :   /home/a/cbpi4/logs*******************************Debug-log-level
is 30******************************* List of active plugins  Name
 Version    Author                               Homepage
                           Summary--------  ---------
 -----------------------------------
 ----------------------------------------------------
 ---------------------------cbpi4gui  0.3.13     Manuel Fritsch / Alexander
Vollkopf  https://openbrewing.gitbook.io/craftbeerpi4_support/
<https://openbrewing.gitbook.io/craftbeerpi4_support/>  CraftBeerPi4 User
Interface *

The created examples are not available

If I
 pipx runpip cbpi4 install cbpi4-system

The plugin is created installed and available*.  *The plugin is in a hidden
directory

/home/a/.local/share/pipx/venvs/cbpi4/lib/python3.10/site-packages

I would also like to know your thought about crafterberrpi for PC.  I have
made two plugins that enable easy use of craftbeerpi on a PC.

1) plugin that enables a arduino for use as GPIO using   asynchronous
telemetrix.  Arduinos are so cheap and have hardware pwm.  I have not
implemented IP connection ,but should be fairly easily possible for
multiple Arduino's
2) plugin using OWFS and a dongle for one wire temps ( and other devices
such as flowmeter)

Should this be a seperate fork.

Thanks

**Comment by avollkopf** [comment]
Still impossible to support without log file information and/or plugin code

**Comment by avollkopf** [comment]
Closed, as there is no feedback / code example since Feb 23
