### ISSUE TITLE
Add Sensor Temperature Offset to MQTTSensor

### ISSUE THREAD

**Issue by stamandster** [PiBrewing/craftbeerpi4#139]
I'm not sure how to adjust the code myself, or else I'd do it. But it would be great to add the option to adjust Temp Offset just like the Onewire Sensor. Unfortunately, for things like Tasmota, sometimes the source only allows adjustment of ALL sensors on the device.

**Comment by avollkopf** [comment]
If I remember correctly, this has been discussed in the past and we somehow decided to not implement it as it should be corrected at the sensor itself to avoid double correction. But I will re-review it, once I have successfully updated the brewfather api calls.

**Comment by stamandster** [comment]
I appreciate that @avollkopf . I know it's not a little thing to add this, but just having the option is super helpful for me. If you do adjust it, I think it's good to consider adding a little description that says something like "Be careful not to duplicate Temperature Offsets, make change here or at the sensor."

**Comment by lalo-uy** [comment]
You can add individual offsets at Tasmota with rules.
Catch the original mqtt msg, add the offset and publish the new value on a
different topic.

**Comment by stamandster** [comment]
Yes, I know that is a potential, however in order to get 1s reads I need to query Status8 via HTTP at 1s interval with a python script. This is provides the existing temperature not the offset adjusted using the rule.

**Comment by lalo-uy** [comment]
Ok, but a 20L kettle have a lot of thermal inertia, 10s teleperiod is quite
ok.
In a RIMS a short cicle could have sense.

**Comment by stamandster** [comment]
Yes, RIMS is the primary application. Though, another use case for this could be used during recirculation through the chiller for a whirl pool hop addition to make sure the incoming wort through the chiller is being adequately chilled to reach a specific whirl pool temperature. Also, I run my pump during the ramp to boil so that there's turbulence and mixture of cold/hot pockets within the liquid mass. The tele 10s period is too long in both situations.

**Comment by avollkopf** [comment]
Latest version in dev branch has changes to address your request. Install version, it'll add a parameter mqtt_offset to config.yaml. Default is false. Set it manually to yes and restart cbpi -> Offset for mqtt sensor plugin is enabled. By reverting mqtt_offset to false, parameter is disabled in mqtt sensor plugin
