### ISSUE TITLE
Cant create recipe from beerxml

### ISSUE THREAD

**Issue by 2bbe** [PiBrewing/craftbeerpi4#149]
Im trying to create a Recipe from a Beersmith 3 beerxml file without success.
The dropdown is empty as you can see in the picture bleow:
![image](https://github.com/user-attachments/assets/d22e16d8-604f-4341-b9e2-77443dc8572e)
The upload seems ok since the file _~/config/uplad/beer.xml_ updates according to the uploaded file.
It seems to work with a beerxml from brewfather.
file used for test:
[test.xml.txt](https://github.com/user-attachments/files/17894238/test.xml.txt)

**Comment by avollkopf** [comment]
Your exported xml file has an issue in line 194
![image](https://github.com/user-attachments/assets/28115db6-6bde-43f9-b30f-52f4c43fdf18)

This **SOH** or whatever it is not real ascii text. Not sure what it is. If I remove the SOH, the file is shown in the drop down menu.

![image](https://github.com/user-attachments/assets/830c7152-63e7-4551-aa33-e7bbe5d6e1f3)

**Comment by avollkopf** [comment]
I assume this has been clarified and I will close it here

**Comment by 2bbe** [comment]
Yeah, thanks for the info. 
Now I just have to find out why I get this...
