### ISSUE TITLE
image-url for docker creation needs to be lowercase -> to be adapted

### ISSUE THREAD

**Issue by avollkopf** [PiBrewing/craftbeerpi4#95]

**Comment by avollkopf** [comment]
@papauorg Same issues have been described here: https://github.com/orgs/community/discussions/25768

Maybe you can find a solution faster than i would :-)

**Comment by avollkopf** [comment]
@papauorg , @dereulenspiegel 

Although, the image seems to be build correctly, it cannot be pushed:
```
ERROR: failed to solve: failed to push ghcr.io/pibrewing/craftbeerpi4:dev: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/pibrewing/craftbeerpi4:dev: unexpected status: 403 Forbidden
```
Adding write permissions in the build.yml did not help.

Not sure, if settings in the org need to be changed:
![image](https://user-images.githubusercontent.com/43980694/223433741-88ffd846-3935-4d9f-b3ce-708ed777c6dc.png)

Currently, I have no rights to change that setting

**Comment by papauorg** [comment]
@avollkopf Yes, I think that's it. It should look like this:
![image](https://user-images.githubusercontent.com/2471424/223438442-2b2ad2cc-412c-4ba7-8f37-ef725e98e048.png)

Not sure if it has something to do with the casing, too. We'll see when the permissions are set ... :)

**Comment by avollkopf** [comment]
> 
> Edit:
> 
> > Not sure, if settings in the org need to be changed:
> 
> I not sure how this is done in an org, but the permissions can usually be set on repository level

Right, I was also referring to the repo and not the entire org. But here I can't change the setting to 'Read and Write'

**Comment by papauorg** [comment]
Hm, strange. I would expect the owner of the org to be allowed to change the repos settings. But otherwise we could try setting the permissions in the workflow file directy:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

**Comment by avollkopf** [comment]
Could change only the orgs global settings. Now repo settings have been changed and are flexible. Flow went through
